version: '2.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Taipei
    mem_limit: 5125m
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    #healthcheck:
    #  test: "/usr/bin/mysql --user=root --password=password --execute=\"SHOW DATABASES;\""
    #  interval: 3s
    #  timeout: 3s
    #  retries: 20

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
    - 3000:3000
    environment:
    - MB_DB_FILE=/metabase-data/metabase.db
    - JAVA_TIMEZONE=Asia/Taipei
    volumes:
    - ./volumes/metabase-data:/metabase-data
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    depends_on:
      - "mysql"
